apiVersion: v1
kind: Namespace
metadata:
  name: kubepwn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubepwn
  namespace: kubepwn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubepwn
  template:
    metadata:
      labels:
        app: kubepwn
    spec:
      containers:
      - name: kubepwn
        image: kubepwn-app:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        volumeMounts:
        - name: host-root
          mountPath: /host
        - name: containerd-sock
          mountPath: /run/containerd/containerd.sock
      volumes:
      - name: host-root
        hostPath:
          path: /
          type: Directory
      - name: containerd-sock
        hostPath:
          path: /run/containerd/containerd.sock
          type: Socket
---
apiVersion: v1
kind: Service
metadata:
  name: kubepwn-service
  namespace: kubepwn
spec:
  selector:
    app: kubepwn
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
