config:
  clients:
    - url: http://loki:3100/loki/api/v1/push

  positions:
    filename: /tmp/positions.yaml

  snippets:
    extraScrapeConfigs: |
      - job_name: falco
        static_configs:
          - targets:
              - localhost
            labels:
              job: falco
              __path__: /var/log/pods/falco_*/falco/*.log

  server:
    http_listen_port: 3101
    grpc_listen_port: 0
