- rule: Read of Sensitive Kubernetes Configs
  desc: Detect access to admin kubeconfig or etcd secrets
  condition: >
    open_read and
    (fd.name contains "/etc/kubernetes/admin.conf" or fd.name contains "/etc/kubernetes/pki/" or fd.name contains "kubeconfig")
  output: >
       [K8s Secrets Read] Accessed sensitive config: %fd.name by %proc.cmdline
  priority: HIGH
  tags: [k8s, secrets, privilege_escalation]
