apiVersion: v1
kind: Config
clusters:
- name: kubernetes
  cluster:
    server: https://kubepwn-control-plane:6443
    insecure-skip-tls-verify: true
contexts:
- name: backdoor-context
  context:
    cluster: kubernetes
    user: backdoor
current-context: backdoor-context
users:
- name: backdoor
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlpuckRCd3RDeEhIWFM2X2Ztakh5RmtkemtrUDJlV2FTTXdxUk9rcjFVQ1UifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzU3NDMxODU0LCJpYXQiOjE3NTc0MjgyNTQsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiN2E5YzgyYTEtZWU3Yy00ZDQ0LTgyOTctMGM1ZjJlY2RiMmZhIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJiYWNrZG9vci1zYSIsInVpZCI6IjUzNmMwMGI4LTFmYTYtNGY2Ny1iOTU2LTM3MTU5NzYzODM4ZSJ9fSwibmJmIjoxNzU3NDI4MjU0LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06YmFja2Rvb3Itc2EifQ.dQ6-xHZ0NmUBzPiwN8QC89Fa3N8YaDG2hmXyEPIFxNOMQBbEc30smQ9L391PnKYvfg3GB6gLET9jgfpsZGncMYtkCrAAPk-RxQ0v_7bTV6LXyBoylra_LXTyv7V2vhMWEmkFJVMZqN3b8ICTA1JTbGCem5soFnJjmwg9V1iPtkwhAah328eKUGAivsSTVI4M9eguRvVfRkr-zlnG4oLOVxwab_KIT6BshwOfxcDtvFHMxykt6uz1N4vDWPcR3cXLspbTn9dl4SaTVU1k8mAzBtDB2eo9tWsqCL2GVxvKJsnJTBwvSNWbZ7jak1rcU4nW3s0G2HvsEi1fdYZ0WRi77g



#echo -e "apiVersion: v1\nkind: Config\nclusters:\n- name: kubernetes\n  cluster:\n    server: https://kubepwn-control-plane:6443\n    insecure-skip-tls-verify: true\ncontexts:\n- name: backdoor-context\n  context:\n    cluster: kubernetes\n    user: backdoor\ncurrent-context: backdoor-context\nusers:\n- name: backdoor\n  user:\n    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlpuckRCd3RDeEhIWFM2X2Ztakh5RmtkemtrUDJlV2FTTXdxUk9rcjFVQ1UifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzU3NDMxODU0LCJpYXQiOjE3NTc0MjgyNTQsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiN2E5YzgyYTEtZWU3Yy00ZDQ0LTgyOTctMGM1ZjJlY2RiMmZhIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJiYWNrZG9vci1zYSIsInVpZCI6IjUzNmMwMGI4LTFmYTYtNGY2Ny1iOTU2LTM3MTU5NzYzODM4ZSJ9fSwibmJmIjoxNzU3NDI4MjU0LCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06YmFja2Rvb3Itc2EifQ.dQ6-xHZ0NmUBzPiwN8QC89Fa3N8YaDG2hmXyEPIFxNOMQBbEc30smQ9L391PnKYvfg3GB6gLET9jgfpsZGncMYtkCrAAPk-RxQ0v_7bTV6LXyBoylra_LXTyv7V2vhMWEmkFJVMZqN3b8ICTA1JTbGCem5soFnJjmwg9V1iPtkwhAah328eKUGAivsSTVI4M9eguRvVfRkr-zlnG4oLOVxwab_KIT6BshwOfxcDtvFHMxykt6uz1N4vDWPcR3cXLspbTn9dl4SaTVU1k8mAzBtDB2eo9tWsqCL2GVxvKJsnJTBwvSNWbZ7jak1rcU4nW3s0G2HvsEi1fdYZ0WRi77g" > kubeconfig.yaml
