apiVersion: v1
kind: ServiceAccount
metadata:
  name: lateral-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: lateral-sa
  namespace: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
# Simulated Secret for Extraction
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  username: YWRtaW4=     # base64(admin)
  password: c2VjcmV0      # base64(secret)
---
apiVersion: v1
kind: Pod
metadata:
  name: lateral-move
  namespace: default
spec:
  serviceAccountName: lateral-sa
  containers:
  - name: curl-container
    image: alpine:latest
    command: ["/bin/sh", "-c"]
    args:
      - apk add --no-cache curl jq && sleep 3600
  restartPolicy: Never
