apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-db
  template:
    metadata:
      labels:
        app: metadata-db
    spec:
      containers:
      - name: metadata-db
        image: metadata-db:latest  # should match your built image tag
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: metadata-db
spec:
  selector:
    app: metadata-db
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  clusterIP: None
