apiVersion: v1
kind: Service
metadata:
  name: ssrf-service
spec:
  type: NodePort
  selector:
    app: ssrf-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssrf-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssrf-app
  template:
    metadata:
      labels:
        app: ssrf-app
    spec:
      containers:
      - name: ssrf-app
        image: kubepwn-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
