apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: allow-node-impersonation
rules:
- apiGroups: [""]
  resources: ["users"]
  verbs: ["impersonate"]
- apiGroups: [""]
  resources: ["groups"]
  verbs: ["impersonate"]
